# Generated by Django 3.2.7 on 2021-10-02 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacionUsuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Persona',
            new_name='Usuario',
        ),
    ]
