# Generated by Django 3.2.7 on 2021-10-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacionUsuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('nombre_usuario', models.CharField(max_length=45)),
                ('contraseña', models.CharField(max_length=45, null=True)),
                ('descripcion', models.TextField()),
                ('telefono', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=60)),
                ('correo', models.EmailField(max_length=80)),
                ('terminos_condiciones', models.BooleanField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('nombre_usuario', models.CharField(max_length=45)),
                ('contraseña', models.CharField(max_length=45, null=True)),
                ('descripcion', models.TextField()),
                ('telefono', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=60)),
                ('correo', models.EmailField(max_length=80)),
                ('terminos_condiciones', models.BooleanField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
