# Generated by Django 3.2.7 on 2021-10-02 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacionUsuarios', '0002_rename_persona_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=140)),
                ('telefono', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=60)),
                ('correo', models.CharField(max_length=80)),
            ],
        ),
    ]
