# Generated by Django 3.2.7 on 2021-10-05 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacionUsuarios', '0002_auto_20211003_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencia',
            name='contraseña',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='agencia',
            name='descripcion',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='agencia',
            name='direccion',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='agencia',
            name='nombre_usuario',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='agencia',
            name='telefono',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='agencia',
            name='terminos_condiciones',
            field=models.BooleanField(null=True),
        ),
    ]
