# Generated by Django 3.2.7 on 2021-10-05 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacionUsuarios', '0003_auto_20211005_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencia',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
