# Generated by Django 3.2.7 on 2021-10-05 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacionUsuarios', '0004_alter_agencia_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='contraseña',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='descripcion',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre_usuario',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='terminos_condiciones',
            field=models.BooleanField(null=True),
        ),
    ]
