# Generated by Django 3.2.7 on 2021-10-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('codigoRuta', models.BigAutoField(primary_key=True, serialize=False)),
                ('ciudadOrigen', models.CharField(max_length=40)),
                ('ciudadDestino', models.CharField(max_length=40)),
                ('precio', models.FloatField()),
                ('fechaIda', models.DateField()),
                ('fechaVuelta', models.DateField()),
                ('descuento', models.FloatField()),
            ],
        ),
    ]
